version: "3.9"

services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - FLAG=flag{flag_here}
      - WAF_COOKIES=1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.novel.rule=Host(`novel.easonabc.eu.org`)"
      - "traefik.http.services.novel.loadbalancer.server.port=8000"
