// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_article_id_ from "./routes/api/article/[id].ts";
import * as $api_novel_delete_id_ from "./routes/api/novel/delete/[id].ts";
import * as $api_novel_reload_id_ from "./routes/api/novel/reload/[id].ts";
import * as $api_novel_translate_id_ from "./routes/api/novel/translate/[id].ts";
import * as $article_id_ from "./routes/article/[id].tsx";
import * as $index from "./routes/index.tsx";
import * as $novel_id_page_ from "./routes/novel/[id]/[[page]].tsx";
import * as $partial_novel_id_page_ from "./routes/partial/novel/[id]/[page].tsx";
import * as $unsupported_url_ from "./routes/unsupported/[url].tsx";
import * as $ActionButton from "./islands/ActionButton.tsx";
import * as $ArrowButton from "./islands/ArrowButton.tsx";
import * as $HistoryEntry from "./islands/HistoryEntry.tsx";
import * as $LoadButton from "./islands/LoadButton.tsx";
import * as $PrefetchAnchor from "./islands/PrefetchAnchor.tsx";
import * as $PrefixComplete from "./islands/PrefixComplete.tsx";
import * as $StartButton from "./islands/StartButton.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/article/[id].ts": $api_article_id_,
    "./routes/api/novel/delete/[id].ts": $api_novel_delete_id_,
    "./routes/api/novel/reload/[id].ts": $api_novel_reload_id_,
    "./routes/api/novel/translate/[id].ts": $api_novel_translate_id_,
    "./routes/article/[id].tsx": $article_id_,
    "./routes/index.tsx": $index,
    "./routes/novel/[id]/[[page]].tsx": $novel_id_page_,
    "./routes/partial/novel/[id]/[page].tsx": $partial_novel_id_page_,
    "./routes/unsupported/[url].tsx": $unsupported_url_,
  },
  islands: {
    "./islands/ActionButton.tsx": $ActionButton,
    "./islands/ArrowButton.tsx": $ArrowButton,
    "./islands/HistoryEntry.tsx": $HistoryEntry,
    "./islands/LoadButton.tsx": $LoadButton,
    "./islands/PrefetchAnchor.tsx": $PrefetchAnchor,
    "./islands/PrefixComplete.tsx": $PrefixComplete,
    "./islands/StartButton.tsx": $StartButton,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
