services:
  novel:
    image: ghcr.io/eason0729/novel-tralslate:latest
    restart: unless-stopped
    environment:
      - SQLITE_PATH=/data/database.sqlite3
      - "API_URL=http://ollama:11434"
      - "WAF_COOKIES=aws-waf-token=get_one_if_you_want_alphapolis.co.jp;"
    volumes:
      - "./data:/data"
    ports:
      - "8080:8000"
    networks:
      - ollama
  ollama:
    build:
      context: .
      dockerfile: ollama-Dockerfile
    restart: unless-stopped
    networks:
      - ollama
networks:
  ollama: {}